# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.32
# 

Name:       aria2

# >> macros
# << macros
%define spectacle_bug hack_fix
# Spectacular spectacle hack: 
#   abuse Macros to work around the Macro-deleting bug in 0.32 
#   also, add a conditional dep:
%if 0%{?sailfishos_version} >= 30400
BuildRequires: pkgconfig(libcares)
%endif

Summary:    A utility for downloading files
Version:    1.37.0
Release:    0
Group:      Applications/Internet
License:    GPLv2
URL:        https://aria2.github.io
Source0:    %{name}-%{version}.tar.bz2
Source100:  aria2.yaml
BuildRequires:  pkgconfig(libssl)
BuildRequires:  pkgconfig(libxml-2.0)
BuildRequires:  pkgconfig(sqlite3)
BuildRequires:  pkgconfig(zlib)
BuildRequires:  autoconf
BuildRequires:  automake
BuildRequires:  libtool
BuildRequires:  gettext-devel
BuildRequires:  openssh
BuildRequires:  ( pkgconfig(libgpg-error) or pkgconfig(gpg-error) )

%description

aria2 is a utility for downloading files. The supported protocols are
HTTP(S), FTP, SFTP, BitTorrent, and Metalink.

aria2 can download a file from multiple sources/protocols and tries to
utilize your maximum download bandwidth. It supports downloading a file
from HTTP(S)/FTP/SFTP and BitTorrent at the same time, while the data
downloaded from HTTP(S)/FTP/SFTP is uploaded to the BitTorrent swarm. Using
Metalink's chunk checksums, aria2 automatically validates chunks of data
while downloading a file like BitTorrent.

%if "%{?vendor}" == "chum"
Title: Aria2
Type: console-application
PackagedBy: nephros
Categories:
 - Internet
 - Utility
Custom:
  Repo: https://github.com/aria2/aria2
  PackagingRepo: https://github.com/sailfishos-chum/aria2.git
Links:
  Homepage: https://aria2.github.io
  Help: https://aria2.github.io/manual/en/html/index.html
%endif


%package devel
Summary:    Development files for %{name}
Group:      Development/Libraries
Requires:   libaria2 = %{version}-%{release}

%description devel
%{summary}.

%package -n libaria2
Summary:    C++ library which offers %{name} functionality
Group:      Development/Libraries
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig

%description -n libaria2
%{summary}.

%if "%{?vendor}" == "chum"
Title: libaria2
PackagedBy: nephros
Categories:
 - Library
Custom:
  Repo: https://github.com/aria2/aria2
  PackagingRepo: https://github.com/sailfishos-chum/aria2.git
Links:
  Homepage: https://aria2.github.io
  Help: https://aria2.github.io/manual/en/html/index.html
%endif


%prep
%setup -q -n %{name}-%{version}/upstream

# >> setup
# << setup

%build
# >> build pre
# << build pre

%reconfigure --disable-static \
    --enable-libaria2 \
    --disable-nls \
    --with-pic \
    --with-bashcompletiondir=%{_datadir}/bash-completion/completions \
    --without-gnutls --with-openssl

make %{?_smp_mflags}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
rm -rf %{buildroot}%{_mandir}
rm -rf %{buildroot}%{_docdir}
# << install post

%post -n libaria2 -p /sbin/ldconfig

%postun -n libaria2 -p /sbin/ldconfig

%files
%defattr(-,root,root,-)
# >> files
%{_bindir}/*
%{_datadir}/bash-completion/completions/*
# << files

%files devel
%defattr(-,root,root,-)
# >> files devel
%{_includedir}/*
%{_libdir}/*.so
%{_libdir}/pkgconfig/*.pc
# << files devel

%files -n libaria2
%defattr(-,root,root,-)
# >> files libaria2
%{_libdir}/*.so.*
# << files libaria2
